pytorch/examples

- logreg/main.py
When learning how to use pytorch, I found it useful to write this example. I tried to rely on low-level operations rather than high-level abstractions to make it clear what's going on.
Feel free to close this - it's probably too basic for an example. I just thought I'd make the PR so others can find it in case it's useful.
> Add logistic regression example

- mnist_hogwild/main.py
multiprocessing in python 2.7 doesn't support multiprocessing.set_start_method method - so we'll skip it
> Make mnist_hogwild python 2.7 compatible

- imagenet/main.py
PR #28 had a bug that it listed models' module names (i.e. vgg, resnet) among the architectures. This PR fixes the problem.
> Remove module names from arch list in Imagenet example

- dcgan/main.py
Similarly to the Torch example, this reuses the fake image that was created for the discriminator (and hence the forward pass of the generator).
Checked that the expected backwards passes are occurring using hooks, and have also run the example to check that it's working fine empirically.
> Prevent 2 forward passes with detach

- mnist/README.md
Related to #72
Is this information available in docs?
> Add instruction to use specified GPU id

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
If the agent never experienced reward, rewards turns into nan (0/0). We should add machine epsilon to the denominator here to avoid that.
> fixed divide by zero error

- OpenNMT/onmt/Models.py
- OpenNMT/onmt/Translator.py
- OpenNMT/preprocess.py
- OpenNMT/train.py
- OpenNMT/translate.py
Changes necessary to use OpenNMT with nn.DataParallel.
Reference https://github.com/adamlerer/examples/pull/1
-  While it does train correctly, additional GPUs appear to slow down training. Perhaps this is due to issues similar to those towards the end of https://discuss.pytorch.org/t/does-it-support-multi-gpu-card-on-a-single-node/75. If anyone has more familiarity with using nn.DataParallel with RNNs, I'd love to chat about how to remedy this (or at least figure out a more precise diagnosis).
- There's likely a cleaner way to refactor the code to avoid so many transposes. I initially did not want to change the logic that was used in the original batching code to ensure correctness, but this is something I can look into further if the transposes are an issue.
> Multi-GPU OpenNMT

- imagenet/main.py
With flush, log info can appear immediately when it is directed to a pipe or file.
> add flush to print

- word_language_model/model.py
To address https://github.com/pytorch/examples/issues/83
I did it in this way so that the command line interface to the program would not have to change (i.e: you could still pass `--model RNN_TANH` as described in the help for `model` in the argument parser), but if it is desirable to change that we can make the fix a little bit cleaner.
> Command Line Interface backwards compatible fix for models.py

- imagenet/main.py
> Revert "add flush to print"

- word_language_model/main.py
Minimal change: essentially removing code that now duplicates code included in PyTorch's built-ins. This also fixes a potential bug that was reported regarding reaching the same perplexity numbers reported in the code.
Fixes #95.
> Replace clip_gradient with torch's newly included clip_grad_norm

- OpenNMT/onmt/Dataset.py
Hi, I have changed the calculation method for batch number, since it will crash when dataset is smaller than 64. Since if dataset number is smaller than 64, `self.numBatches` will be 0 and will lead to crash.
> Change the calculation method of the batch number. 

- word_language_model/README.md
- word_language_model/main.py
- word_language_model/model.py
This is as close to SotA as I can get from a standard LSTM without a form of recurrent dropout (see: https://github.com/pytorch/pytorch/issues/561).
Parameters are similar to [Recurrent Neural Network Regularization (Zaremba et al. 2014)](https://arxiv.org/pdf/1409.2329.pdf) and include the one line tweak from [Tying Word Vectors and Word Classifiers: A Loss Framework for Language Modeling (Inan et al. 2016)](https://arxiv.org/pdf/1611.01462.pdf) that substantially improves perplexity whilst minimizing the number of parameters.
This also serves as a better learning example now as well, given it includes dropout (including the use of `model.train()` and `model.eval()`) and also saves / reloads the model with best validation loss.
> PTB LM example now has far better perplexity for both large (72.30) and small (87.17) models

- word_language_model/README.md
- word_language_model/model.py
As written in both Inan et. al. (2016) and Press & Wolf (2016), weight tying in RNN language models was developed in parallel by both of these teams, and so I've updated the attribution in the code to include both.
> update attribution of weight tying in word_language_model

- OpenNMT/.gitignore
- OpenNMT/README.md
- OpenNMT/onmt/Dataset.py
- OpenNMT/onmt/Dict.py
- OpenNMT/onmt/Models.py
- OpenNMT/onmt/Optim.py
- OpenNMT/onmt/Translator.py
- OpenNMT/onmt/modules/GlobalAttention.py
- OpenNMT/preprocess.py
- OpenNMT/train.py
- OpenNMT/translate.py
Done:
- fixes bug in translate when user wishes to use cpu by passing -1 as device number
- removes re-initialization of checkpoint parameters
- replaces chunking with splitting
- removes unnecessary opt.cuda
- replace pre-ModuleList code with ModuleList
- converts to int when user wants to use the start_decay_at argument
-  fixes issue with decoder hidden state (https://github.com/pytorch/examples/issues/88)
- replaces from-scratch gradient clipping with nn.utils.clip_grad_norm
- adds additional logging for source and target tokens per second
- fixed: index was set to 0 in the translate.py code for printing the n best
- fixed: len was applied the batch (always giving batch size) rather than the top prediction for each batch when counting the total number of predicted words in …
> ONMT fixes and updates

- word_language_model/generate.py
The model in the word language model example uses dropout, so I add a line to call model.eval() before generation.
> Switch the model to evaluation mode before generation in the language model example

- mnist/main.py
- mnist_hogwild/main.py
As far as I am concerned, `softmax(relu(h_last))` is a very unusual thing to do. Removed the rectifier for convergence and didactic purposes as discussed [here](https://discuss.pytorch.org/t/relu-in-mnist-example/1190/2).
> Remove rectifier before softmax

- word_language_model/main.py
humber->number
--batch-size->--batch_size
> some wrong typing

- dcgan/main.py
Using single GPU in DCGAN caused an error because  'gpu_ids'  in forward function will be None .
> fix a bug in DCGAN when using single gpu

- time_sequence_prediction/train.py
open without 'rb' caused Python 3 to open this in text mode and fail
> Fix Python 3 issue with time_sequence_prediction

- snli/model.py
Python 2.* does not support ``out.view(*size, -1)''. Expand it to ``out.view(size[0], size[1], -1)''.
File "train.py", line 9, in <module>
from model import SNLIClassifier
File "snli/model.py", line 13
return out.view(*size, -1)
SyntaxError: only named arguments may follow *expression
> snli/model.py: can run using Python 2.*

- mnist/main.py
Change the help message for `--no-cuda`, explaining it *disables* CUDA, not *enables* it as currently written. The joy of boolean optional command line arguments :)
> Fix help message for no-cuda

- mnist_hogwild/main.py
- mnist_hogwild/train.py
Since gradients are allocated lazily, they are instantiated in every process separately on the `loss.backward()` call. The removed lines in train.py are no longer needed.
> mnist_hogwild manual breaking of gradient sharing removed

- snli/train.py
Making it hopefully a bit easier to understand for pytorch novices.
No code changes.
> added comments in snli/train.py

- mnist/main.py
Found one bug in MNIST.
1. Go to this line: [MNIST main script](https://github.com/pytorch/examples/blob/master/mnist/main.py#L106)
So this code assumes that we have same number of data points in each batch, which actually not the case. And more accurate way should be multiply NNL_loss of each batch by its batch-size, and get the sum over whole data set, then divide it by the data set size.
2. The parameter `epoch` in [`test()` function](https://github.com/pytorch/examples/blob/master/mnist/main.py#L92) is useless. So we may as well remove it.
> Bugs In MNIST

- snli/train.py
- snli/util.py
since there is #145, here is another pull request to fix the problem that the `exist_ok` parameter of `os.makedirs()` does not exist in python < 3.2 (in particular it does not exist in python 2.7)  .
> added a function makedirs() to snli example which works both for python 2 and 3

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
Since the gym package has changed, maximum step number is 200 in the cartpole environment, so the mean reward was unable to reach 200, and both reinforce and actor_critics scripts were never ending.
This fix replace the hard coded 200 step by env.spec.reward_threshold.
In the future and to avoid such cases were an updated package broke things, maybe 
`pip freeze > requirements.txt`
would help by freezing the current (and therefore working) version of each package ?
> reinforcement_learning fix reward threshold

- mnist/main.py
The batch size for the training set was erroneously used for instantiating the DataLoader class for the test set.
> Change test DataLoader to use the test batch size

- vae/main.py
Fixes:
```
UserWarning: Using a target size (torch.Size([16, 1, 28, 28])) that is
different to the input size (torch.Size([16, 784])) is deprecated.
Please ensure they have the same size.
```
on PyTorch v0.2.0.
Second commit removes unnecessary branch I found during debugging.
> vae: Fix `UserWarning`

- time_sequence_prediction/train.py
The time series prediction example is somewhat misleading. In a multilayer LSTM, h (the hidden state or output) rather than c should be fed into the next layer or output as the prediction. For the sine wave, the network learns to predict either way, but I believe the example should be fixed to show the correct use.
> h rather than c should be fed into the next layer of LSTM

- time_sequence_prediction/train.py
- word_language_model/main.py
I found it a bit hard to follow the layout produced by batchify and get_batch and thought I'd write down what I learned. Also fixes a minor typo in time_sequence_prediction.
> Document the data layout in word_language_model

- time_sequence_prediction/train.py
As is the final network output is modulated with a tanh nonlinearity.
This is undesirable. As a simple / realistic fix we add a final
linear layer.
This addresses #243.
> Add linear layer to time series prediction

- dcgan/main.py
- fast_neural_style/neural_style/neural_style.py
- imagenet/main.py
- super_resolution/data.py
[Do not merge until next torchvision release]
[PR 274](https://github.com/pytorch/vision/pull/274) in torchvision renames `Scale` to `Resize` and `RandomSizedCrop` to `RandomResizedCrop` - this updates the examples.
> Scale -> Resize + RandomSizedCrop -> RandomResizedCrop

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
`torch.distributions.Multinomial` doesn't exist in v0.3.0, but `torch.distributions.Categorical` does
> fix reinforcement_learning example

- vae/main.py
Replace 2-space with 4-space indentation
> Fix indentation to be self-consistent

- mnist/main.py
- mnist_hogwild/main.py
Currently, running `python mnist/main.py` outputs the following:
````
mnist/main.py:68: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
return F.log_softmax(x)
````
and `python mnist_hogwild/main.py` outputs
````
mnist_hogwild/main.py:45: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
return F.log_softmax(x)
````
The output of these warnings to stderr can cause errors in systems that run `mnist/main.py` as a test script to check installation of PyTorch. To easily reproduce, run `python mnist/main.py > /dev/null`.
In both cases, `log_softmax` is always applied to a two-dimensional tensor with shape `batch_size x num_classes` and so the …
> Fix UserWarning in two examples

- vae/main.py
Summation is consistent with notation in the paper. Results are still fine (test reconstructions and samples, noting that this VAE doesn't use conv layers and so results won't necessarily be as good):
Closes https://github.com/pytorch/examples/issues/234 and https://github.com/pytorch/examples/issues/290.
> Fix VAE losses (sum over everything)

- mnist/main.py
Fixes some warnings when indexing a 0-d array and potential overflow since Variable `sum()` returns the same type as the source tensor
> Fixes for Tensor and Variable merge

- word_language_model/main.py
After https://github.com/pytorch/pytorch/pull/5785, the concrete type of all Tensor/Variable objects will be torch.Tensor. We should use `isinstance` instead of exact type checks.
> Fix type check on hidden state

- mnist/main.py
This is simple restructure of code without any logic changes so that now it has proper main() function.
This is required because it otherwise does not run on Windows. This PR fixes issue: https://github.com/pytorch/examples/issues/352. More info on fix is [here](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection).
> Convert to proper script with main(), fix #352

- fast_neural_style/neural_style/neural_style.py
Fix the following error when --export_onnx is enabled for fast_neural_style:
`$ python neural_style/neural_style.py eval --model saved_models/rain_princess.pth --export_onnx saved_models/rain_princess.onnx --content-image images/content-images/img.jpg --output-image images/output-images/img.jpg --cuda 1`
> Traceback (most recent call last):
File "neural_style/neural_style.py", line 240, in <module>
main()
File "neural_style/neural_style.py", line 236, in main
stylize(args)
File "neural_style/neural_style.py", line 150, in stylize
utils.save_image(args.output_image, output[0])
File "/fast_neural_style/neural_style/utils.py", line 15, in save_image
img = data.clone().clamp(0, 255).numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory …
> fix fast_neural_style --export_onnx

- word_language_model/main.py
Description: As per the torch 0.4 documentation, torch.nn.utils.clip_grad_norm has been deprecated in favor of torch.nn.utils.clip_grad_norm_, this commit corrects the deprecated usage in word_language_model/main.py
> Updated clipping to torch.nn.utils.clip_grad_norm_

- vae/main.py
The reparameterize() function should not be deterministic for validation/test mode. It should be the same as in training mode, otherwise what is computed is not the ELBO (i.e. the correct loss) but something else. This change will slightly change the test set error.
> Fix bug in reparameterize() in VAE example

- imagenet/main.py
This pull request is to update all the occurrences of precision to accuracy in imagenet/main.py to be consistent with the accuracy definition.
> Update all prec occurrences to acc in imagenet tutorial

- snli/train.py
The default value of `repeat` of `iterator` class is `False` in [the current stable version of torchtext](https://github.com/pytorch/text/releases/tag/0.3.1).
So [this line](https://github.com/pytorch/examples/blob/master/snli/train.py#L61) is not necessary now.
> Use torchtext 0.3.1

- imagenet/README.md
- imagenet/main.py
Added multiprocessing mode for distributed training. This will use `torch.multiprocessing.spawn` for both single node and multi-node training.
Tested by verifying the following works:
(1) Single Node Single GPU
(2) Single Node Multi GPU
(3) multiprocessing single node Multi GPU distributed
(4) non-multiprocessing single node multi GPU distributed
> [Distributed] Multiprocessing Distributed Training for ImageNet Example

- imagenet/main.py
Unified order of flag names in argparser: short flag names ('-f') go before long flag names ('--foo').
> Unified order of flag names in argparser

- imagenet/main.py
For multiple long options, python takes the first as attribute name by default. The latest commit swapped the order of options that causes the script an error (e.g., AttributeError: 'Namespace' object has no attribute 'weight_decay'). Added dest option to explicitly specify the valid attribute name.
> Fix broken args order

- reinforcement_learning/actor_critic.py
Original:
```
parser.add_argument('--seed', type=int, default=543, metavar='N',
help='random seed (default: 1)')
```
Fixed:
```
parser.add_argument('--seed', type=int, default=543, metavar='N',
help='random seed (default: 543)')
```
> Fix a typo in the `actor_critic` example

- mnist/main.py
Thanks for great examples!
For beginners, I thought using `.argmax()` will be better than using `.max()[1]`.
> Use argmax() instead of max()[1] in mnist/main.py

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
In response to some confusion in Slack, I've revisited the RL examples. The code to track the `running_reward` was mixed with number of timesteps, which is true for this environment but not in general, so this now makes it explicitly tracking reward only (cc @ebetica). I've also replaced (where appropriate), `rewards` with `returns`, which is actually what is happening. Run the code, everything works fine.
> Tidy var names for RL examples

- imagenet/main.py
Lines 245 and 246 will always FAIL when a checkpoint is saved while running this code on a specific GPU, then something happens stopping training, then training is resumed on a different GPU. The error occurs because best_acc1 and acc1 are on different GPUs but are compared. This is a least-number-of-lines bug fix that does not impact other use cases.
> Fixes bug when loading checkpoint of different GPU

- reinforcement_learning/reinforce.py
1. Dropout layer can significantly improve the performance and the problem is solved within 1000 episodes. In contrast, the original code seems not converge even after 10 thousand episodes.
2. Shift to CartPole-v1 which is a more challenging task than v0.
Credit: https://medium.com/@ts1829/policy-gradient-reinforcement-learning-in-pytorch-df1383ea0baf
Thanks,
Xurui
> Add dropout layer in reinforce.py

- cpp/dcgan/dcgan.cpp
I ran the example codes for [C++][DCGAN] but the 2 if statements in the nested for loop are not behaving as expected. The first one just prints the losses every epoch essentially since batch_index gets value 1 through the life of the program. As for the second one it seems to not save anything for the same reason as the first. Not sure if this code runs perfectly fine on other versions as I ran it on C++14. If I'm in the wrong then sorry I wasted your time with this PR.
Thanks
> [C++][DCGAN] Increment batch_index before the if statements?

- imagenet/main.py
This refactors the printing of the progress during the ImageNet training / evaluation. To achieve this every `AverageMeter` now has a `name`, a value format (`fmt`), and a  `__str__()` method for easy printing.
Furthermore, the new `ProgressMeter` bundles the `AverageMeter`s to ease up the interface even more.
> Refactor print progress of ImageNet training

- mnist_hogwild/train.py
Argument is unnecessary in latest 1.0.1 and throws an error
> Remove duplicated argument

- cpp/dcgan/dcgan.cpp
The current log display is not displayed at the "kLogInterval" interval, but is displayed with the "kCheckpointEvery", now fix the problem
> [C++][DCGAN] Log print Error

- imagenet/README.md
The first example shows ResNet using the default learning rate (lr=0.1). However, the multiple GPU and multi-node examples show a lr=0.01 (which is the suggested learning rate for VGG and AlexNet). I assume this is a typo.
> Consistent learning rate for ResNet in readme

- fast_neural_style/download_saved_models.py
PyTorch #18758 moves _download_utl_to_file module path.
This patch considers it
> Consider PyTorch 1.1 for _download_url_to_file module path

- cpp/dcgan/dcgan.cpp
- word_language_model/README.md
- word_language_model/generate.py
- word_language_model/main.py
- word_language_model/model.py
Apply recently developed PyTorch Transformer model for the word language problem. Any reviews and suggestions are appreciated. Please don't land this PR until the transformer model is fully supported by PyTorch. @cpuhrsch @soumith
> Apply Transformer model for the word language problem in pytorch/examples

- word_language_model/data.py
The use of this variable was removed 6 days ago in this PR/merge: https://github.com/pytorch/examples/pull/555
> Removing unused variable

- vae/README.md
The authors had renamed the paper to 'Auto-Encoding Variational Bayes'. This is more familiar to the current research community. I have just renamed the README to its current title, which matches their ICLR 2013 version.
> Reflecting the change in VAE paper name

- imagenet/main.py
This change is necessary for --resume and --evaluate methods when --gpu is specified. For example, if the model was trained on GPU 3 (on a machine with four GPUs: 0, 1, 2, and 3) and then you try to evaluate it on a machine with only 3 GPUs, you would get this error: 
RuntimeError: Attempting to deserialize object on CUDA device 3 but torch.cuda.device_count() is 3. Please use torch.load with map_location to map your storages to an existing device.
This change allows --evaluate and --resume functionalities to work correctly when a single GPU is used.
> Fix load model when a single GPU is used

- cpp/mnist/mnist.cpp
According to [3397d4](https://github.com/pytorch/pytorch/commit/3397d41b8af2824495faaefc649c3c7e47f03bfb) in pytorch repo, which
1) Wrapped namespace `Reduction` in namespace `at`
2) Prefixed `at::` wherever `Reduction::` is used
It should be updated, unless it raise error: ‘Reduction’ has not been declared.
> Prefixed `at::` wherever `Reduction::` is used

- mnist/main.py
Just a small formatting fix for mnist/main.py to make the code compliant  with the PEP8 styleguide.
> Fix formatting to comply with PEP8

- mnist/main.py
Tiny change, simply fix typo in the help string for --epochs.
> MNIST Example: Correct typo in default value within help

- cpp/mnist/mnist.cpp
Issue #672 
- Changed the at::Reduction::Sum into Reduction::Sum
- with at namespace build is failing. without the at namespace, build successfully.
Ref: #672 
fixed: #672 
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>
> fix: Namespace issue of Reduction in CPP MNIST

- cpp/dcgan/CMakeLists.txt
- cpp/regression/CMakeLists.txt
- cpp/transfer-learning/CMakeLists.txt
According to [Tutorial Error for "Using the PyTorch C++ Frontend" #31037](https://github.com/pytorch/pytorch/issues/31037)
The latest libtorch version has been using some cpp 14 features. If we use cpp 11 for compile, it may import some errors like this `error: #error You need C++14 to compile PyTorch`
So I'm trying to update these demos.
> update CXX compiler from 11 to 14

- cpp/dcgan/dcgan.cpp
- cpp/mnist/mnist.cpp
Changes in this PR:
MNIST:
1. `torch::nn::FeatureDropout` is deprecated in favor of `torch::nn::Dropout2d`.
2. `Reduction` enum class lives in `torch::` namespace now.
DCGAN:
1. `Conv2dOptions` no longer has `transposed` argument. All use sites of `Conv2dOptions` with `transposed=true` are changed to using `ConvTranspose2d` layers instead.
2. `ConvTranspose2d` layer cannot be used in a `Sequential` module at the moment (see note in PR description of https://github.com/pytorch/pytorch/pull/31005). To get around this problem in the tutorial, we remove the use of `ConvTranspose2d` in a `Sequential` module.
3. For `ConvTranspose2dOptions`, `with_bias` is renamed to `bias`, matching the Python API and following changes in v1.4.0.
4. `torch::nn::Functional` is deprecated in favor of the …
> Update C++ frontend examples for v1.4.0

- run_python_examples.sh
Fixes #685
This script uses some bash-specific features such as
- `function` keyword
- `==` operator
- `FUNCNAME`
> Fix shebang in `run_python_examples.sh`

- dcgan/main.py
Fixes #698 
```sh
cd dcgan
python main.py --dataset fake
```
> dcgan: using `fake` dataset still requires dataroot parameter

- regression/main.py
In `regression/main.py`, the method `poly_desc()` creates a string description of a polynomial.
IMO, the polynomial coefficients should be from 1 up to 4, not 4 to 1, because `make_features()` method create a matrix with columns `[x, x^2, x^3, x^4]`.
> change regression/poly_desc()

- word_language_model/main.py
- word_language_model/model.py
After removal of the CrossEntropyLoss, loss calculation for RNN is broken.
Currently it's taking NLLLoss of direct RNN output (not the LogSoftmax), resulting in negative losses.
> fix loss calculation for RNN

- distributed/rpc/rnn/main.py
`dist_autograd()` and `dist_optimizer.step` now explicitly take in the `context_id`. This PR reflects the API change in the RPC-based RNN training example.
These API changes will be a part of the PyTorch 1.5 Release.
> [Dist Autograd - API Change] Updated dist_autograd and dist_optim to be functional

- mnist/main.py
This argument (called `args` ) is not used.
> Remove unused argument for test method.

- distributed/rpc/pipeline/README.md
- distributed/rpc/pipeline/main.py
- distributed/rpc/pipeline/requirements.txt
This example shows how to use RPC to implement pipeline parallelism. This can be viewed as a distributed version of [single machine multiple GPU pipeline parallelism](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html#speed-up-by-pipelining-inputs).
The numbers below show how the total execution time decreases with the increase of `num_split`.
```
$ python main.py 
Processing batch 0
Processing batch 1
Processing batch 2
number of splits = 1, execution time = 16.45062756538391
Processing batch 0
Processing batch 1
Processing batch 2
number of splits = 2, execution time = 12.329529762268066
Processing batch 0
Processing batch 1
Processing batch 2
number of splits = 4, execution time = 10.164430618286133
Processing batch 0
Processing batch 1
Processing batch 2
number of …
```
> Adding distributed pipeline parallelism example

- .gitignore
- distributed/rpc/pipeline/main.py
This PR fixes the error in `distributed/rpc/pipeline/main.py`. Here is how it looks like:
```
distributed/rpc/pipeline$ python ./main.py
File "./main.py", line 286, in <module>
mp.spawn(run_worker, args=(world_size, num_split), nprocs=world_size, join=True)
File "/anaconda/envs/mypytorchenv_gpu/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/anaconda/envs/mypytorchenv_gpu/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
while not context.join():
File "/anaconda/envs/mypytorchenv_gpu/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
raise Exception(msg)
Exception:
-- …
```
> Correcting the pipeline rpc example

- distributed/rpc/parameter_server/rpc_parameter_server.py
This fixes incorrect arguments passed to `model.forward` in the RPC Parameter Server training example.
> Fix Parameter Server Example

- dcgan/main.py
- distributed/rpc/pipeline/main.py
- distributed/rpc/rnn/rnn.py
- regression/main.py
- word_language_model/main.py
- word_language_model/model.py
Following https://github.com/pytorch/pytorch/pull/34211, this PR removes all direct accesses to the `.data` attribute.
> Eliminate .data access for parameters as much as possible

- cpp/mnist/CMakeLists.txt
Fixes error: `error: You need C++14 to compile PyTorch`.
Related: https://github.com/pytorch/pytorch/issues/31037
> Fix cpp/mnist CMakeList build.

- word_language_model/model.py
`nn.init.zeros_(self.decoder)` throws this error `AttributeError: module 'torch.nn.init' has no attribute 'zero_'` because the weights weren't passed.
> [word_language_model] Fix initialization of weight of Decoder

- distributed/rpc/parameter_server/README.md
Parameter Server example launch command was previously `---world_size=2`. This PR changes it to `--world_size=2`
> Fix parameter server command line options in README

- word_language_model/main.py
`p.add_(-lr, p.grad)` throws `RuntimeError: a leaf Variable that requires grad is being used in an in-place operation`, using `p.data.add_(-lr, p.grad)` fixes this issue.
> [word_language_model] Fix grad in-place operation

- word_language_model/README.md
This PR fixes an inconsistency in the description of optional arguments between README and the actual outputs of `python main.py --help`.
> Update word-level LM arguments in README

- run_python_examples.sh
- time_sequence_prediction/requirements.txt
This fixes errors I ran into running the PyTorch examples
> Fix errors executing run_python_examples.sh "install_deps,run_all"

- word_language_model/model.py
Model was not getting initialized property since it was using the
decoder object instead of decoder weight to initialize zeros.
Closes https://github.com/pytorch/examples/issues/783
Solution can be attributed to @mjoukamaa
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> word_language_model: Fix Transformer init_weights

- dcgan/main.py
- imagenet/main.py
- mnist/main.py
- mnist_hogwild/main.py
- mnist_hogwild/train.py
- run_python_examples.sh
- snli/train.py
- snli/util.py
- time_sequence_prediction/train.py
- word_language_model/main.py
Tweak the `run_python_examples.sh` script to complete in ~5 minutes (on my machine) without CUDA. Once this is merged, we can consider adding #704 to actually run the examples as part of CI.
TBD: how do we get a pre-release version of torch/torchvision in order to test the latest HEAD? Perhaps it should be a pytorch/pytorch cron job that runs once a day or once a week?
ping @jlin27
> tweak running examples without cuda

- distributed/rpc/batch/README.md
- distributed/rpc/batch/parameter_server.py
- distributed/rpc/batch/reinforce.py
- distributed/rpc/batch/requirements.txt
This PR adds two examples for `@rpc.functions.async_execution` decorator.
1. A synchronized batch-pdate Parameter Server example.
2. A batch-processing reinforcement learning example.
> Adding Batch RPC example

- .github/workflows/main.yml
- README.md
xref pytorch/pytorch#32004
Run github actions CI once a day (at 3:00) and if it fails, open an issue. mattip/pytorch-examples#21 is a forced example of such an issue. A few things to note:
- The main purpose of this action is to consistently test this repo against pytorch nightly builds, to see if some new pytorch "feature" breaks one of the examples.
- Anyone who forks this repo will, by default, get this scheduled action. I added a note to the README. We could also add a step to emit an issue `if {{ github.repository_owner != 'pytorch' }}` which would hopefully get people's attention :). By default forks do not have issues, so I am not sure what would happen. Forking this repo does seem like a popular thing to do: there are 64.k forks. Searching for a way to disable via the yml led me …
> Run CI daily

- imagenet/main.py
Per title. Layout of `pred` is now correctly propagated so that `correct` is not contiguous.
> use reshape instead of view in accuracy

- distributed/rpc/batch/parameter_server.py
- distributed/rpc/ddp_rpc/main.py
- distributed/rpc/pipeline/main.py
Summary: Since TensorPipe is going to be the default backend in 1.7, we
should change our examples to use this backend. Some examples were
failing since the default was TensorPipe but we were passing in
ProcessGroupBackendOptions.
Test Plan: Run the test examples.
> Fix RPC examples to use TensorPipeRpcBackendOptions.

- time_sequence_prediction/train.py
This PR simplifies some lines in `time_sequence_prediction/train.py`.
* The variable `i` in line 25 is unused.
* The combination of `torch.stack` and `torch.squeeze` in line 35 can be replaced with a `torch.cat`.
* `input.chunk(input.size(1), dim=1)` in line 25 is identical to `input.split(1, dim=1)`.
The last 2 changes might not be necessary, so please let me know if you want me to undo them. Thanks!
> Simplify some lines in time_sequence_prediction

- mnist/main.py
Using dropout2d does not really make sense for the second dropout since the data is flattened at that point (but it works accidentally). Furthermore, since this example copies the one from Keras (https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py) it might be better to follow that example (regular dropout). 
No noticeable performance changes.
> MNIST example: use regular dropout rather than dropout2d

- fast_neural_style/neural_style/utils.py
Convert loaded image to RGB to avoid size mismatch for an RGBA image
```python 
img = Image.open(filename).convert('RGB')
```
> Convert loaded image to RGB in Fast Neural Style

- distributed/ddp/README.md
- distributed/ddp/example.py
The change can help users run ddp example on Windows directly.
So far, only gloo and filestore are supported on Windows
> support ddp example on Windows

- cpp/dcgan/README.md
I rewrote the wrong extension.
dcgan-sample-10.**png** => dcgan-sample-10.**pt**
thank you.
> [fix] wrong file extention in cpp-dcgan-README

- cpp/regression/README.md
I found a typo error in **examples/cpp/regression/README.md**.
`cd mnist` => `cd regression`
It's a little difference, but important.
Thank you for GOOD EXAMPLES :)
> [fix] Rewrite typo in the Readme of cpp-regression

- fx/module_tracer.py
In this example, we are going to define a custom `fx.Tracer` instance that--
for each recorded operation--also notes down the qualified name of the module
from which that operation originated. The _qualified name_ is the path to the
Module from the root module. More information about this concept can be
found in the documentation for `Module.get_submodule`:
https://github.com/pytorch/pytorch/blob/9f2aea7b88f69fc74ad90b1418663802f80c1863/torch/nn/modules/module.py#L385
> [FX] Add example of tracer that records module qualname for each node

- distributed/rpc/pipeline/main.py
- Higher timeout is required when running on ROCm
as the required kernels are compiled at runtime.
> [ROCm] Increasing the rpc timeout

- fx/subgraph_rewriter_basic_use.py
The generated code is wrong, which shouldn't has `sum` op after running `replace_pattern`.
> fix the error of generated code in subgraph rewrite

- fx/primitive_library.py
Add an example for defining a library of "composable primitives", that is, functions that appear literally in the graph by default but can be decomposed into more fine-grained operations on request. We demonstrate decomposing operations both with an API during graph manipulation as well as automatically during tracing with a custom Tracer
> [FX] Add primitive library example

- distributed/ddp/example.py
The tutorial otherwise uses zero-indexed ranks throughout, so this change makes the example mentioned in the comment in `demo_basic()` follow the same convention.
No testing was performed since this only edits comments.
> Fix comment to use zero-indexed ranks

- fx/inline_function.py
- fx/primitive_library.py
- fx/proxy_based_graph_creation.py
Summary:
Replaced Proxy(object) creations with Proxy(object, GraphAppendingTracer)
which ensures graceful handling of n-ary operators.
By default Proxy creates a new tracer when no tracer arg
is provided, these examples encourage use of Proxy creation
with the GraphAppendingTracer when dealing with n-ary operators.
Implements cases outlined in pytorch/pytorch#68195
Test Plan:
```bash
python fx/inline_function.py
python fx/proxy_based_graph_creation.py
python fx/primitive_library.py
```
No errors on the above and output of `fx/primitive_library` confirmed
to be the same as inline commented expected output. Also verified  via
diff of OG output and updated output.
FYI: `fx/nnc_compile.py` might need this fix too, but I was not able to run
the script at all. Threw the following error: …
> Updating retracing examples to handle n-ary operators

- snli/train.py
proposed fix for #942
According to Torchtext 0.9.0 release note:
- torchtext.data.Field -> torchtext.legacy.data.Field
- torchtext.data.Dataset -> torchtext.legacy.data.Dataset
https://github.com/pytorch/text/releases/tag/v0.9.0-rc5
> change torchtext to torchtext.legacy

- word_language_model/generate.py
`word_language_model/generate.py` fails to use a model file trained with CUDA on a machine without CUDA.
- run `cd word_language_model && python main.py` on a machine with CUDA.
- copy `model.pt` to a machine without CUDA.
- run `cd word_language_model && python generate.py` on a machine without CUDA.
It shows
```
File "generate.py", line 47, in <module>
model = torch.load(f).to(device)
File "/home/kaiida/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
File "/home/kaiida/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
result = unpickler.load()
File …
```
>  word_language_model/generate.py reads a model file trained with CUDA, into CPU if CUDA is not available.

- word_language_model/model.py
Weights of decoders are initialized twice. I think we need to call the zeros_() to initialize bias.
> Fix Transformer init_weights

- .github/workflows/main.yml
- distributed/rpc/batch/reinforce.py
- distributed/rpc/rl/main.py
- distributed/rpc/rnn/rnn.py
This PR includes updates to change the default branch from master to main.
Fixes #71844 from pytorch repo.
> #71844 Migrate default branch to main.

- distributed/rpc/batch/reinforce.py
- distributed/rpc/rl/main.py
I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue when I was parsing/generating from the TensorFlow—and now PyTorch—codebases: inconsistent use of `Args:` and `Arguments:` in its docstrings. It is easy enough to extend my parsers to support both variants, however it looks like `Arguments:` is wrong anyway, as per:
- https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
- https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
- …
> [*.py] Rename "Arguments:" to "Args:"

- docs/source/conf.py
Adding the Google Analytics code to track examples usage at pytorch.org/examples.
> Add Google Analytics code

- .gitignore
- CONTRIBUTING.md
- docs/source/index.rst
- run_python_examples.sh
- siamese_network/README.md
- siamese_network/main.py
- siamese_network/requirements.txt
I have followed `mnist/main.py` setup and modified it a bit to include the definition of `Siamese Network` and custom configuration of `MNIST` set but for the `Object Matching` task.
This PR was created per https://github.com/pytorch/examples/issues/645
> Implemented a Siamese Network Example

- reinforcement_learning/reinforce.py
env.seed is deprecated and this PR updates that to env.reset, which gets rid of the warning message.
> env.seed is deprecated, change to env.reset

- distributed/rpc/parameter_server/rpc_parameter_server.py
Bug fix for https://github.com/pytorch/examples/issues/1023
Tested it in Mac with CPU, in Linux with CPU and 2 GPUs(aws p3.8xlarge instance with Amazon Linux/RHEL).
> [parameter_server] fix deadlock in multiprocessing by using spawn

- imagenet/README.md
- imagenet/main.py
we add a method to use dummy data for performance benchmark only, this feature will save a lot of time for downloading real ImageNet Dataset, this is a part of #1011
> refine imagenet dummy part of #1011

- imagenet/main.py
Use of torch.FloatTensor causes an issue with the NCCL backend, which only supports DistributedDataParallel primitives on GPU. This results in a runtime error "Tensors must be CUDA and dense".
This commit implemented a condition which checks if torch.cuda.is_available() and if so instead uses torch.cuda.FloatTensor to resolve the runtime error for the NCCL backend.
> Fix for NCCL backend, all_reduce performed on GPU when available

- mnist_hogwild/main.py
Related to issue: https://github.com/pytorch/examples/issues/1037
> fix: prevent "context has already been set" error in mnist_hogwild example 

- run_python_examples.sh
The dcgan test is flaky as reported in https://github.com/pytorch/examples/issues/1038 and https://github.com/pytorch/examples/issues/1040 
The root cause is that it's very slow to download the "classroom" dataset from http://dl.yf.io/
To make the test script more stable, let's use fake data in `run_python_examples.sh`. The test time for dcgan is reduced from minutes to ~5 seconds.
Test plan:
```
./run_python_examples.sh dcgan
```
> Fix flaky dcgan test by using fake data

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
Description:
- Currently RL examples are not working with the latest open [gym v0.26.0](https://github.com/openai/gym/releases/tag/0.26.0)
- replaced deprecated `env.seed` call in `actor_critic.py`
- updated code of both examples with new ouptut of `env.reset()` and `env.step()`
> Fixed RL examples to work with new gym API

- imagenet/main.py
> fix imagenet nondeterminism when seed is set (#1056)

- dcgan/README.md
- dcgan/main.py
- fast_neural_style/README.md
- fast_neural_style/neural_style/neural_style.py
- imagenet/main.py
- legacy/snli/train.py
- mnist/main.py
- mnist_hogwild/main.py
- run_python_examples.sh
- siamese_network/main.py
- super_resolution/README.md
- super_resolution/main.py
- vae/README.md
- vae/main.py
- word_language_model/README.md
- word_language_model/main.py
Added mps device to some networks
> Add mps device

- distributed/ddp-tutorial-series/slurm/config.yaml.template
- distributed/ddp-tutorial-series/slurm/sbatch_run.sh
- distributed/ddp-tutorial-series/slurm/setup_pcluster_slurm.md
Second PR for the DDP tutorial series. This code accompanies the tutorials staged at https://github.com/pytorch/tutorials/pull/2049
This PR includes code for slurm cluster setup and multinode training on slurm.
> Add code for DDP tutorial series [PR 2 / 3]

- word_language_model/generate.py
After training a model in Mac with mps option, when trying to run the generate script it is giving a Runtime error "Placeholder storage has not been allocated on MPS device". To avoid this issue, this change is made
> Added mps option in generate.py

- imagenet/main.py
It's due to `image` and `model` are in GPU but `target` is still in CPU. As the device is already determined in main(), we don't have to do it again in train(). We can pass device to train() and move data to the same device as model.
```
python main.py -a resnet50 --dist-url tcp://127.0.0.1:1234 --dist-backend nccl --multiprocessing-distributed --world-size 1 --rank 0 --epochs 3 --batch-size 256 -j64 --dummy
```
> Fix device mismatch issue in #1071

- reinforcement_learning/reinforce.py
The function finish_episode() in the reinforce.py script computes returns by insertion at the beginning of a list.
This is an expensive computation in python as shown by the official docs, since it requires O(N) time to shift all its successor elements. 
The same can be achieved but with O(1) time complexity with the python deque data structure, natively supported by python.
To verify the above claims, i tested insertion of 100k elements at the beginning of a list and a deque.
The results are:
- list insertion at the beginning -> 1 second
- deque insertion at the beginning -> 0.004 seconds
Hence, this is a 250 x speed-up, which becomes relevant when the number of episodes becomes large, as this computation is done at the end of every episode.
Python docs Reference: …
> Speed-up to O(1) from O(N)  of the computation of each return in REINFORCE  

- distributed/ddp-tutorial-series/multinode.py
Fixes #1078 to use `map_location` when saving and loading models on different devices
> Add map_location when loading model checkpoint

- imagenet/main.py
- mnist_rnn/main.py
- run_python_examples.sh
mnist_rnn is introduced in https://github.com/pytorch/examples/pull/752 We need to cover it in the test script for CI.
Test plan:
```bash
./run_python_examples.sh mnist_rnn
```
> add mnist_rnn to test script for CI

- fx/wrap_output_dynamically.py
CI is broken(https://github.com/pytorch/examples/issues/1087) due to `assert_allclose` is removed in PyTorch, we should replace it with assert_close()
Test plan:
> [fix CI] replace assert_allclose with assert_close

- cpp/transfer-learning/classify.cpp
**Why**
Lineanr model `model_linear` is loaded in function `print_probabilities`. So line 75 and line 76 can be removed.
> Remove unused code from /cpp/transfer-learning/classify.cpp

- word_language_model/main.py
When running the word language model on Jetson NX, the original main.py fails caused by that torch (NVIDIA offical pytorch docker image: `l4t-pytorch:r35.1.0-pth1.11-py3`) do not have the `mps` backend. This modification has fixed the problem.
> word language model on Jetson NX

- distributed/ddp-tutorial-series/multigpu.py
- distributed/ddp-tutorial-series/multigpu_torchrun.py
- distributed/ddp-tutorial-series/multinode.py
- distributed/ddp-tutorial-series/single_gpu.py
This corrects a minor bug in the `distributed/ddp-tutorial-series` scripts where explicitly setting the batch size via `--batch_size` throws a `ValueError`.  
Running,
```
cd distributed/ddp-tutorial-series
python single_gpu.py --batch_size 32 1 1
```
Produces the following error:
```
File "/local/scratch/3162385/examples/distributed/ddp-tutorial-series/single_gpu.py", line 82, in <module>
main(device, args.total_epochs, args.save_every, args.batch_size)
File "/local/scratch/3162385/examples/distributed/ddp-tutorial-series/single_gpu.py", line 68, in main
train_data = prepare_dataloader(dataset, batch_size)
File "/local/scratch/3162385/examples/distributed/ddp-tutorial-series/single_gpu.py", line 58, in prepare_dataloader
return DataLoader(
File …
```
> set type of batch_size argument to int in ddp-tutorial-series

- distributed/ddp-tutorial-series/multinode.py
I fixed a small bug in the ddp multinode tutorial which does not allow the loading of snapshots (`AttributeError: 'Trainer' object has no attribute 'gpu_id'`). It looks like the `_load_snapshot` method was copied over from `multigpu_torchrun.py` but the attribute `gpu_id` was not renamed to `local_rank`.
> fix: fixed local device name in multinode example.

- word_language_model/README.md
`generate.py` does not accept a `--model` argument, it just uses the default checkpoint (unless you specify `--checkpoint` argument).
> Remove reference to non-existing `--model` argument

- distributed/ddp-tutorial-series/multigpu.py
- distributed/ddp-tutorial-series/multigpu_torchrun.py
- distributed/ddp-tutorial-series/multinode.py
- distributed/minGPT-ddp/mingpt/main.py
The recommended best practice to avoid hangs and high memory utilization on GPU:0 is to `set_device(i)` which switches the default from GPU:0 to GPU:i
> Adds torch.cuda.set_device calls to DDP examples

- legacy/snli/README.md
📘🚀 Introduced a comprehensive README outlining the project overview and detailed usage instructions for the SNLI Classifier training scripts.
> 📝🎯 Added README for SNLI Classifier Training

- distributed/minGPT-ddp/mingpt/main.py
Fix simple import error
```sh
File "mingpt/main.py", line 29, in main
ddp_setup()
File "mingpt/main.py", line 13, in ddp_setup
torch.cuda.set_device(int(os.environ["LOCAL_RANK"]))
NameError: name 'os' is not defined
```
> Fix import in minGPT example

- distributed/rpc/batch/parameter_server.py
In PyTorch 2.0, the default setting of "set_to_none" in "zero_grad" is True, which leads to TypeError when accumulating gradients in BatchUpdateParameterServer.
Ref:
[torch.optim.SGD.zero_grad in PyTorch 2.0](https://pytorch.org/docs/2.0/generated/torch.optim.SGD.html?highlight=zero_grad#torch.optim.SGD.zero_grad)
[torch.optim.SGD.zero_grad in PyTorch 1.13](https://pytorch.org/docs/1.13/generated/torch.optim.SGD.html?highlight=zero_grad#torch.optim.SGD.zero_grad)
> fix zero_grad default parameter

- distributed/rpc/rl/main.py
- distributed/rpc/rl/requirements.txt
Reflect newer gym in the RPC RL example as [gym](https://github.com/openai/gym) moves to [gymnasium](https://github.com/Farama-Foundation/Gymnasium) and the current example does not work with gymnasium or newest gym version. [Reference](https://gymnasium.farama.org/content/migration-guide/)
> Use gymnasium and reflect new API

- word_language_model/model.py
#1112  I fix this issue by simplifying TransformerModel using nn.Transformer module.
P.S. I have also tried that starting from an nn.Module super class, but there is a custom decoder (nn.Linear) used in this example, which makes the example more complicated if we combine it with nn.Transformer.
> Update TransformerModel using nn.Transformer module

- cpp/transfer-learning/convert.py
- fast_neural_style/neural_style/vgg.py
For TorchVision models, `pretrained` parameters have been deprecated in favor of "Multi-weight support API" - see https://pytorch.org/vision/0.15/models.html
> [TorchFix] Update deprecated TorchVision pretrained parameters

- distributed/tensor_parallelism/fsdp_tp_example.py
We now have a new DeviceMesh API `get_local_rank` so users would no longer need to get the underlying pg and then get the local rank from it.
> [2D] Update 2d example to use get_local_rank

- cpp/dcgan/dcgan.cpp
The cpp/dcgan shape warning has been discussed in https://github.com/pytorch/examples/issues/819. This PR adopted the solution mentioned in the issue and tested with the up-to-date libtorch (2.1.2) with cuda 12.1 using both the release and debug build.
> Fix the DCGAN C++ shape warning

- cpp/autograd/CMakeLists.txt
- cpp/custom-dataset/CMakeLists.txt
- cpp/dcgan/CMakeLists.txt
- cpp/distributed/CMakeLists.txt
- cpp/mnist/CMakeLists.txt
- cpp/regression/CMakeLists.txt
- cpp/transfer-learning/CMakeLists.txt
Update the cmake minimum version per cmake deprecation warning:
```
[cmake] CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
[cmake]   Compatibility with CMake < 3.5 will be removed from a future version of
[cmake]   CMake.
```
> update-minimum-cmake-version to version 3.5

- vision_transformer/main.py
When saving model's learned parameters the class token and positional embedding parameters where not saved. This happened because these parameters where lost when moving the model to the GPU (as explained [here](https://discuss.pytorch.org/t/empty-state-dict-after-moving-model-to-gpu/21069)). I guess this was the reason different tensors where returned when running with the same weights loaded from the saved model, as mentioned [here](https://github.com/pytorch/examples/issues/1184#issuecomment-1783659171).
> Bugfix in vision transformer - save class token and pos embedding

- cpp/custom-dataset/README.md
- cpp/custom-dataset/custom-dataset.cpp
1. Update the Caltech 101 dataset URL in readme.
2. `random_shuffle`: is not a member of 'std' since it c++17, updated to `shuffle`.
3. `Functional(torch::log_softmax, 1, torch::nullopt)` no longer matches the constructor, updated to lambda expression.
4. `auto tlabel = torch::from_blob(&data[index].second, {1}, torch::kLong);` sometimes leads to non-sensical numerical value. 
A few examples from std::cout:
```
data[index].second: 42 
tlabel:  42 [ CPULongType{1} ] 
data[index].second: 10 
tlabel:  10 [ CPULongType{1} ] 
data[index].second: 98 
tlabel:  4.6698e+16
```
Updated to direct the creation of a tensor instead of creation from a pointer.
Tested the program via libtorch (2.1.2) with cuda 12.1 using both the release and debug build.
> Update the readme and fix bugs in custom-dataset example

- .github/workflows/main_cpp.yml
- cpp/custom-dataset/CMakeLists.txt
- run_cpp_examples.sh
Include a CI job for cpp/custom-dataset, we have to use **libtorch-cxx11-abi-shared-with-deps** since libtorch-shared-with-deps is `not` compatible with openCV, reported [here](https://discuss.pytorch.org/t/library-conflict-between-libtorch-and-opencv/64489).
If use libtorch-shared-with-deps, then the error will be encountered as
> Include a CI job for cpp/custom-dataset

- cpp/custom-dataset/custom-dataset.cpp
The `data` variable loads from the info.txt and encodes the info in pair <image path, ground truth label>.
The program should not modify this information during the execution and thus ensure the const-ness of the `data` variable.
Tested the program via libtorch (2.1.2) with cuda 12.1 using both the release and debug build.
> Ensure the const-ness of the data member

- run_cpp_examples.sh
- Add CI jobs for cpp/mnist and cpp/regression.
- Add a check for run status in the CI jobs. 
- If build fails, the job reports _Failed to build $EXAMPLE_
- If build is successful but fails in run the complied excutable, the job reports _Failed to run $EXAMPLE_
> Add CI jobs for cpp/mnist and cpp/regression

- run_cpp_examples.sh
Add a CI job for cpp/dcgan. 
Currently, run cpp test costs 2h 12m 35s since 30 epochs of dcgan on CPU is quite time-consuming.
A potential speed-up (not covered in this PR) is to make the number of epochs as a command line arg in cpp/dcgan and run only a few epochs in the CI job.
> Add a CI job for cpp/dcgan

- .github/workflows/main_cpp.yml
- cpp/dcgan/dcgan.cpp
- run_cpp_examples.sh
- Make number of epochs a command line argument, the CI job runs 5 epoch (compared to its default value of 30) to reduce the overall testing time
- Improve code readability by separating the discriminator creation from the main function.
- `const referece` in  `const torch::data::Example<>& batch : *data_loader` is standard (compared with the non-const version ` torch::data::Example<>& batch : *data_loader`).
- fix warning C4244: 'initializing': conversion from 'double' to 'int64_t', possible loss of data and warning C4244: 'initializing': conversion from 'double' to 'const int64_t', possible loss of data 
with change
`const int64_t batches_per_epoch =
static_cast<int64_t>(std::ceil(dataset.size().value() / static_cast<double>(kBatchSize)));`
> Improve code readability and make number of epochs a command line argument

- cpp/custom-dataset/README.md
- cpp/dcgan/README.md
1. In cpp/custom-dataset: add a short remark regarding we should use `libtorch-cxx11-abi-shared-with-deps` instead of `libtorch-shared-with-deps` when seeing an error like undefined reference to cv::imread(std::string const&, int) by running the make command.
2. In cpp/dcgan: add a remark on the `--epochs` flag.
> Improve readme for cpp/custom-dataset and cpp/dcgan

- imagenet/main.py
* issue link referred to hint at single GPU user what to do if nccl internal check error
* nccl required version mentioned
> warning added for single GPU and NCCL

- gcn/main.py
Minor improvement of the GCN doc.
> Minor improvement of the GCN doc

- .github/workflows/main_distributed.yaml
- distributed/tensor_parallelism/README.md
- distributed/tensor_parallelism/fsdp_tp_example.py
- distributed/tensor_parallelism/llama2_model.py
- distributed/tensor_parallelism/requirements.txt
- run_distributed_examples.sh
> Update TP examples to align with tutorials

- gat/README.md
Remove some duplicate words from the  readme.md file
> chore: remove repetitive words

- cpp/tools/download_mnist.py
- run_cpp_examples.sh
The URL `https://ossci-datasets.s3.amazonaws.com/mnist/` is extracted 
via 
```
from torchvision import datasets
datasets.MNIST(".", download=True)
```
output
```
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Failed to download (trying next):
HTTP Error 403: Forbidden
Downloading https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz
Downloading https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz to ./MNIST/raw/train-images-idx3-ubyte.gz
100%|██████████| 9912422/9912422 [00:00<00:00, 14826948.05it/s]
Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Failed to download (trying next):
HTTP Error 403: Forbidden
Downloading …
```
> Fix the MNIST dataset url

- distributed/tensor_parallelism/fsdp_tp_example.py
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1259
Following changes in https://github.com/pytorch/torchtitan/pull/314, to apply a reduce-scatter instead of the more expensive all-reduce + local chunk.
cross PR with https://github.com/pytorch/tutorials/pull/2871
> [Tensor Parallel] update examples to simplify embedding + first transformer block

- mnist/main.py
Remove the unused import in MNIST example.
MNIST example succeeded in the CI
> Remove the unused import in MNIST example

- distributed/FSDP/T5_training.py
- distributed/FSDP/configs/fsdp.py
This fixes https://github.com/pytorch/examples/issues/1210
Enabling AC is enabling compile by default which is then failing to handle the cpu offloading flag for FSDP?
This is broken on 2.2, 2.3 and nightlies
cc @awgu @anijain2305
> Fix AC in T5 example

- distributed/ddp-tutorial-series/multigpu.py
- distributed/ddp-tutorial-series/multigpu_torchrun.py
- distributed/ddp-tutorial-series/multinode.py
Summary:
`set_device` should be called before `init_process_group`.
> Update DDP tutorial for the correct order of set_device

- mnist_forward_forward/main.py
This function is more accurate than torch.log() for small values of input - https://pytorch.org/docs/stable/generated/torch.log1p.html
Found with https://github.com/pytorch-labs/torchfix/
> Use log1p(x) instead of log(1+x)

- .github/workflows/main_python.yml
- dcgan/requirements.txt
- gat/requirements.txt
- gcn/requirements.txt
- imagenet/requirements.txt
- language_translation/requirements.txt
- mnist/requirements.txt
- mnist_forward_forward/requirements.txt
- mnist_hogwild/requirements.txt
- mnist_rnn/requirements.txt
- siamese_network/requirements.txt
- vae/requirements.txt
Summary:
Python tests are failing because of module/version incompatibilities. This change is pulling out the failing tests issue from 
https://github.com/pytorch/examples/pull/1297 into a separate commit so that the 2 changes can be committed independently.
1. Pick specific version of torchvision to fix dependency errors
2. Pin numpy to be below version 2.
3. Update Python version in python tests.
Test Plan:
Tested locally.
> Fix python failing tests

- distributed/FSDP/T5_training.py
- distributed/FSDP/model_checkpointing/checkpoint_handler.py
- distributed/FSDP/requirements.txt
- distributed/FSDP/summarization_dataset.py
- distributed/FSDP/utils/train_utils.py
Summary:
Fix up the FSDP tutorial to get it functional again.
1. Add missing import for load_dataset.
2. Use `checkpoint` instead of `_shard.checkpoint` to get rid of a warning.
3. Add nlp to requirements.txt
4. Get rid of `load_metric` as this function does not exist in new `datasets` module.
5. Add `legacy=False` to get rid of tokenizer warnings.
Test Plan:
Ran the tutorial as follows and ensured that it ran successfully:
```
torchrun --nnodes=1 --nproc_per_node=2 T5_training.py
W1031 09:46:49.166000 2847649 torch/distributed/run.py:793]
W1031 09:46:49.166000 2847649 torch/distributed/run.py:793]
*****************************************
W1031 09:46:49.166000 2847649 torch/distributed/run.py:793] Setting
OMP_NUM_THREADS environment variable for each process to be 1 in
default, to avoid …
```
> [doc][c10d] fixup fsdp tutorial

- fast_neural_style/README.md
- fast_neural_style/neural_style/neural_style.py
Add support for Intel GPU to Fast Neural Style example
> Add support for Intel GPU to Fast Neural Style example

- fast_neural_style/README.md
- fast_neural_style/neural_style/neural_style.py
- fast_neural_style/requirements.txt
- run_python_examples.sh
[torch.accelerator](https://pytorch.org/docs/2.6/accelerator.html) API allows to abstract some of the accelerator specifics in the user scripts. This commit modifies Fast Neural Style example with the mentioned API.
Things to note:
* Commit modifies example command line by replacing accelerator specific flags (`--cuda`, `--mps`, `--xpu`) with the `--accel`.
* `torch.accelerator` API appeared in pytorch 2.6, so commit binds example to this torch version
* Commit introduces `USE_ACCEL` flag for the test `*.sh` script. At the moment this flag is just an alias for `USE_CUDA`. In the future it should replace `USE_CUDA` once all examples will be converted to use `torch.accelerator` API.
CC: @malfet, @atalman
> Use torch.accelerator API in Fast Neural Style example

- .github/workflows/doc-build.yml
- docs/requirements.txt
Update doc-build.yml to fix https://github.com/pytorch/examples/actions/runs/14716493656/job/41300982937 job
- Upgrade actions/checkout from v2 to v4
- Use venv to create the virtual env
- Pin sphinx version to 5.3.0 in requirements.txt with descriptions
CC: @msaroufim
> Update doc-build.yml and requirements for documentation build

- mnist/main.py
- mnist/requirements.txt
- mnist_forward_forward/README.md
- mnist_forward_forward/main.py
- mnist_forward_forward/requirements.txt
- mnist_rnn/README.md
- mnist_rnn/main.py
- mnist_rnn/requirements.txt
- run_python_examples.sh
Refactor MNIST examples to utilize `torch.accelerator` API `torch.accelerator` API allows to abstract some of the accelerator specifics in the user scripts. By leveraging this API, the code becomes more adaptable to various hardware accelerators.
CC: @msaroufim, @malfet
> Use torch.accelerator API in mnist examples

- gat/README.md
- gat/main.py
- gat/requirements.txt
Refactor GAT example to utilize `torch.accelerator` API `torch.accelerator` API allows to abstract some of the accelerator specifics in the user scripts. By leveraging this API, the code becomes more adaptable to various hardware accelerators.
> Use torch.accelerator API in GAT example

- vae/README.md
- vae/main.py
- vae/requirements.txt
Refactor VAE example to utilize torch.accelerator API. torch.accelerator API allows to abstract some of the accelerator specifics in the user scripts. By leveraging this API, the code becomes more adaptable to various hardware accelerators.
CC: @msaroufim, @malfet
> Use torch.accelerator API in VAE example 

- distributed/FSDP2/README.md
- distributed/FSDP2/checkpoint.py
- distributed/FSDP2/model.py
- distributed/FSDP2/train.py
- distributed/FSDP2/utils.py
run FSDP2 on transformer model:
```
torchrun --nproc_per_node 2 train.py
```
* For 1st time, it creates a "checkpoints" folder and save state dicts there
* For 2nd time, it loads from previous checkpoints
To enable explicit prefetching
```
torchrun --nproc_per_node 2 train.py --explicit-prefetch
```
To enable mixed precision
```
torchrun --nproc_per_node 2 train.py --mixed-precision
```
To showcse DCP API
```
torchrun --nproc_per_node 2 train.py --dcp-api
```
> FSDP2 example code for tutorial

- .github/workflows/doc-build.yml
- docs/source/conf.py
This PR Improve docs build ci
**Changes:**
- removed redundant dependencies (`git`, `make`, `python3-venv`) from the GitHub Actions workflow, as they are preinstalled on `ubuntu-latest` runners. 
- Removed deprecated `panels_add_bootstrap_css`
- Created `_static` directory to resolve warnings.
**Testing:**
- Verified locally with `make html` (no errors/warnings).
> This PR Improve docs build ci 

- dcgan/README.md
- dcgan/main.py
- dcgan/requirements.txt
- run_python_examples.sh
Refactor DCGAN examples to utilize torch.accelerator API torch.accelerator API allows to abstract some of the accelerator specifics in the user scripts. By leveraging this API, the code becomes more adaptable to various hardware accelerators.
- Updated dcgan/main.py with accelerator flag 
- Updated README to match dcgan/main.py
- Updated requirements, removed pinned torchvision version
- Updated run_python_examples.sh to match new accelerator flag
CC: @msaroufim, @malfet, @dvrogozh
> Use torch.accelerator in DCGAN example

- run_python_examples.sh
- super_resolution/README.md
- super_resolution/super_resolve.py
- Update CI to run modified super_resolve.py with safe_globals
- Modify README to match main.py example run + formatting
- Add safe_globals for secure code execution of generated model_epoch_x.pth
CC: @msaroufim, @dvrogozh, @jafraustro
> Fix super_resolution example for torch>=2.6

- siamese_network/README.md
- siamese_network/main.py
- vae/README.md
- vae/main.py
This pull request updates the VAE and Siamese examples to restore the default configuration for CI using the Accelerator API. The previous changes inadvertently altered the default settings, which are necessary for consistent CI performance and testing.
Changes:
- Reverted default changes in the VAE example to align with CI requirements.
- Reverted default changes in the Siamese example to align with CI requirements.
- Ensured compatibility with the Accelerator API for both examples.
CC: @msaroufim, @malfet, @dvrogozh
> Restore default CI configuration for VAE and Siamese examples using accelerator API

- run_python_examples.sh
- word_language_model/generate.py
Update example's generate.py usage of torch.load() with required safe globals.
CC: @msaroufim, @dvrogozh, @jafraustro
> Fix torch>= 2.6 generate.py compatibility in Word_language_example

- imagenet/main.py
- run_python_examples.sh
Fixes: dcc2474 ("Add Accelerator Api to Imagenet Example")
CC: @msaroufim, @jataylo, @soumith
> imagenet: fix typo addressing args.gpu

- imagenet/main.py
@eromomon @soumith There is a use_accel not defined issue reported and I proposed a PR to fix it. Please help for the review or ask the maintainer to review. Thanks for your attention.
> Fixed use_accel not defined issue

- mnist/main.py
Since we are setting num_workers to 1, we should either make this worker persistent or not set the num_workers. On my machine, running this script as is takes 2.21 mins, setting the workers to persistent or removing num_workers (setting to its default of 0) makes it a good deal faster at 1.44 and  1.66 mins respectively. 
I would opt for adding the persistent_workers setting as it is a little faster and makes it trivial for even a beginner to speed it up further by increasing the num_workers (setting to 10 reduced my run time to 0.53 mins
> Update main.py tutorial, set persistent_workers, make GPU execution faster

- gcn/README.md
- gcn/main.py
- gcn/requirements.txt
- Add accel argument; update requirements file
CC: @dvrogozh , @msaroufim
> Add `accelerator` API to GCN example.

- distributed/minGPT-ddp/mingpt/main.py
- distributed/minGPT-ddp/mingpt/trainer.py
- distributed/minGPT-ddp/requirements.txt
- distributed/minGPT-ddp/run_example.sh
- run_distributed_examples.sh
Refactor minGPT-ddp example to utilize `torch.accelerator` and `torch.amp`. With these APIs, the code can abstract away specific details related to hardware accelerators, making it more flexible and adaptable to different environments.
CC: @msaroufim @malfet @dvrogozh
> Add torch.accelerator API to minGPT-ddp example

- distributed/tensor_parallelism/fsdp_tp_example.py
After DTensor enhancement, we are not able to use DTensor to handle the change of `num_heads` instead of manually handle the tensor shape while TP is applied.
> Using DTensor to handle local num_heads change while TP is applied

- distributed/tensor_parallelism/fsdp_tp_example.py
In this diff:
- Migrated from FSDP1 to FSDP2 for tp_fsdp example
> Migrate from FSDP1 to FSDP2 for tp_fsdp example
