pytorch/examples

- logreg/main.py
Updates example to deal with breaking change from https://github.com/pytorch/pytorch/pull/454 (https://github.com/pytorch/pytorch/commit/c3eca50c17dee24a79610ba80cbbf45715fdc339).
> Fix logistic regression example

- reinforcement_learning/actor_critic.py
Also changed some initial hyperparams to get it to train faster.
> Actor was not being used in actor-critic

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
> fix argparse type of gamma

- dcgan/main.py
and use os.makedirs py2.7 compatible
> D( G(z).detach() ), added D means for monitoring

- imagenet/main.py
Fix adjust learning rate, the original code does not work with the latest pytorch
> Fix adjust learning rate

- snli/train.py
- snli/util.py
Added loading from snapshot
Updated lowercasing through torchtext
Addressed PyTorch issue https://github.com/pytorch/pytorch/issues/689 with  torch.cuda.set_device(args.gpu)
> Updating with torchtext changes and snapshot loading

- OpenNMT/train.py
See https://github.com/adamlerer/examples/pull/2 and https://github.com/pytorch/examples/pull/50, though merge of https://github.com/pytorch/examples/pull/50 created some conflicts for that particular PR that I believe have been resolved in this one.
> Minor OpenNMT Fixes for Resuming Checkpoint 

- dcgan/README.md
- dcgan/requirements.txt
Added `lmdb` to the dcgan `requirements.txt` as the `LSUN` dataset needs this.
Also added some details to the dcgan README on how to download the LSUN dataset
> Update dcgan requirements and README

- imagenet/main.py
> Fix typo in logging of ImageNet model loading

- dcgan/README.md
- dcgan/main.py
Added `manualSeed` argument and fixed cuda seeding. Also fixed some linting issues and typo.
> Fix random seeding in DCGAN

- super_resolution/README.md
sub-headers were not displaying properly
> update formatting in README

- dcgan/main.py
Fix the bug where generated images are not normalized in DCGAN example.
> apply normalization for output image of dcgan generator

- time_sequence_prediction/README.md
- time_sequence_prediction/generate_sine_wave.py
- time_sequence_prediction/train.py
Hi,
I have made a time sequence prediction example, which I think, is capable to illustrate the usage of LSTMCell in pytorch. It's enough simple and fun and is a good small case for beginners who are interested in either pytorch or time sequence.
> Add a time sequence prediction example

- reinforcement_learning/reinforce.py
It seems to me that `policy` is a better terminology choice than `model`. I was a bit confused when `model` was introduced and I hope this change removes the confusion for future readers. I'm using David Silver's definition:
Policy: agent’s behaviour function
Model: agent’s representation of the environment
But if I'm misunderstanding anything, I'll be very appreciative of any explanation. Thanks!
> replace model by policy

- dcgan/main.py
This should not change the performance of DCGAN but it is perhaps good to teach people to not reuse Variables.
> Change reusing of Variables in DCGAN

- mnist_hogwild/train.py
Similar problem with #175 
Fix same issue in `mnist_hogwild.py`
> fix bugs in generalization error calculation

- fast_neural_style/neural_style/utils.py
This PR fixes error raised during element-wise variable division.
- Fixes #181
> Fix element-wise division for fast-neural-style training. 

- mnist_hogwild/train.py
test_loss /= len(test_loader.dataset) should be test_loss /= len(data_loader.dataset)
> Fix test_epoch typo

- time_sequence_prediction/train.py
Previously the training data input[:3] is incorrectly taken as the test data. Change the input for prediction to data[:3].
> Fix test data in time_sequence_prediction

- super_resolution/model.py
Makes it clearer what is going on in the init as well.
Closes #161
> Use nn.init from core to init SR example

- super_resolution/model.py
Derp, forgot to clean up imports we don't need after https://github.com/pytorch/examples/pull/189
> Remove unused imports in SR example

- super_resolution/model.py
Fixes https://github.com/pytorch/examples/pull/189#event-1175241921
> Change "gain" -> "calculate_gain"

- imagenet/main.py
> Add model_names back. Fixes #195

- time_sequence_prediction/train.py
Fixing the issue of [time sequence prediction broke](https://github.com/pytorch/examples/issues/215)
> change lr to 0.8 to fix the issue for 0.2

- time_sequence_prediction/generate_sine_wave.py
> Remove unused math import

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
> Update RL examples to use torch.distributions instead of reinforce

- reinforcement_learning/actor_critic.py
```
* smooth_l1_loss now requires shapes of arguments to match
* once scalars are enabled, we must use torch.stack() instead of
torch.cat() to turn list of scalars into a Tensor
```
> Fix actor_critic example

- mnist/main.py
- word_language_model/data.py
- word_language_model/main.py
- word_language_model/model.py
This PR fixes a few issues with `mnist` and `word_language_model` to make them work well on current master.
Moving the perf tests off the yf225 account and hosting them under pytorch instead.
> Fixes for perf tests

- word_language_model/main.py
The warnings break the pattern matching in the CI benchmark
> Fix warnings in word_language_model due to Tensor/Variable merge

- dcgan/main.py
Fixed an arg of LSUN according to [update in torchvision](https://github.com/pytorch/vision/commit/73a29e02aff4f30c1d32bcdfa032f6bb72b1bcce#diff-deea30150565e331de97e6ba14a3e119R15).
> Fix arg of LSUN: db_path -> root

- fast_neural_style/neural_style/neural_style.py
- fast_neural_style/neural_style/transformer_net.py
Add onnx export and the capability to run onnx models (using caffe2).
Note: This depends on the fix in https://github.com/pytorch/examples/pull/321
> Onnx export

- word_language_model/main.py
At the end, also save the model in ONNX format.
> Export Word Language Model to ONNX

- super_resolution/super_resolve.py
detach Variable before call numpy()
> fix 0.4 version compliance

- imagenet/main.py
> missing ","

- word_language_model/data.py
Gives problems with Windows default encoding
> open file explicitely using utf-8

- mnist/main.py
Making MNIST example up-to-date with current PyTorch master.
> Fix MNIST example for perf test

- snli/train.py
SNLI data was not tokenized causing bad performance
> Add tokenization for SNLI

- mnist_hogwild/main.py
- mnist_hogwild/train.py
Modified the hogwild example to perform testing outside the different training processes based on discussion [here]](https://discuss.pytorch.org/t/hogwild-training/27614)
> modified the hogwild example

- imagenet/main.py
Fixed:
(1) "env://" init method doesn't work for distributed
(2) in multiprocessing mode, only one process will write the checkpoint
> ImageNet, distributed bug fixes

- imagenet/main.py
Removing `sys` package as it wasn't used. Also, renaming all `input` instances to `predictor` as `input` is a builtin keyword.
> enhancing readability

- imagenet/main.py
> Fix Python 2 compatibility

- imagenet/main.py
> Fix ProgressMeter usage in imagenet validation

- imagenet/main.py
DIVUP args.workers by ngpus_per_node to make sure final workers > 0
> Divide Up args.workers by ngpus_per_node

- cpp/regression/CMakeLists.txt
- cpp/regression/README.md
- cpp/regression/regression.cpp
Here is the c++ version of regression example.
@yf225 @gchanan
> C++ Regression Example

- reinforcement_learning/actor_critic.py
> Added instructive comments

- word_language_model/generate.py
Model may not have attribute 'model_type' (in case of RNNModel)
> Fix 'RNNModel' object has no attribute 'model_type'

- cpp/custom-dataset/CMakeLists.txt
- cpp/dcgan/CMakeLists.txt
- cpp/mnist/CMakeLists.txt
- cpp/regression/CMakeLists.txt
Apply https://github.com/pytorch/pytorch/pull/25556 to this repo.
cc @soumith @ezyang
> Add copy logic for Windows

- cpp/transfer-learning/CMakeLists.txt
- cpp/transfer-learning/README.md
- cpp/transfer-learning/classify.cpp
- cpp/transfer-learning/convert.py
- cpp/transfer-learning/main.cpp
- cpp/transfer-learning/main.h
This PR adds an example of Transfer Learning using `Libtorch` and `OpenCV`.
> Added Transfer Learning using Libtorch and OpenCV

- distributed/rpc/rl/README.md
- distributed/rpc/rl/main.py
- distributed/rpc/rl/requirements.txt
In this example, each observer captures the state from its environment, and send the state to the agent to select an action. Then, the observer applies the action to its environment and reports the reward to the agent.
> Adding an RPC tutorial using a simple reinforcement learning application

- word_language_model/main.py
> bug #714: Remove for double usage of log_softmax 

- vae/README.md
Signed-off-by: nbqu <dk41245@gmail.com>
Added to /vae/README.md some descriptions for optional arguments.
> README.md : Add descriptions for optional arguments

- cpp/autograd/CMakeLists.txt
- cpp/autograd/README.md
- cpp/autograd/autograd.cpp
This accompanies the upcoming C++ autograd tutorial (https://github.com/pytorch/tutorials/pull/921).
> C++ autograd example

- distributed/rpc/parameter_server/README.md
- distributed/rpc/parameter_server/rpc_parameter_server.py
Make parsing command line args consistent
Remove unused arg in the code
> Update RPC param server example

- imagenet/main.py
> loss detach

- imagenet/main.py
> Revert "loss detach"

- regression/main.py
https://github.com/pytorch/examples/pull/779/files did not fix the issue present in regression test
> fix the issue PR #779 left

- mnist/main.py
I'm sorry to suddenly send you a PR. However, I feel uncomfortable with this blank line and send PR.
> Delete unnecessary blank line

- .github/workflows/main.yml
- README.md
- dcgan/main.py
- fast_neural_style/download_saved_models.py
- run_python_examples.sh
- word_language_model/main.py
Add github action to run examples on CPU
> WIP: Add CI to run examples via github action

- README.md
Minor fix of github CI badge for better rendering.
> Updated CI badge

- mnist/main.py
> Fix unused --test-batch-size command line argument

- fx/native_interpreter/CMakeLists.txt
- fx/native_interpreter/README.md
- fx/native_interpreter/interpreter.cpp
- fx/native_interpreter/use_interpreter.py
Creates an `fx` folder and adds an example for lowering PyTorch code into a native runtime
> [FX] Start fx folder and add native interpreter example

- fx/vmap.py
Taken from https://github.com/pytorch/pytorch/pull/51555
> Added vmap example

- fx/nnc_compile.py
Merge after this: https://github.com/pytorch/pytorch/pull/52492
> [FX] updated NNC_compile example

- snli/train.py
> [892] Fix snli train.py typo

- snli/train.py
Fixed typo - replace 'valiation' with 'validation'
> Fix minor typo in comment (#892)

- distributed/rpc/ddp_rpc/main.py
Replace `emb_rref` with `remote_emb_module`.
RemoteModule can be passed like RRef over the wire after https://github.com/pytorch/pytorch/pull/57695.
> Replace RRef with RemoteModule

- fx/wrap_output_dynamically.py
The example inserted the new node in the wrong place. Fix that and add test driver code to make sure this actually works
> [FX] Fix wrap output example

- distributed/rpc/ddp_rpc/main.py
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #924
Summary:
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
> Example code fix for https://github.com/pytorch/tutorials/pull/1619

- dcgan/README.md
Fixes https://github.com/pytorch/examples/issues/675
> updated dcgan docs

- reinforcement_learning/actor_critic.py
- reinforcement_learning/reinforce.py
> Revert "Normalized loss in actor-critic and REINFORCE examples."

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/doc_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CONTRIBUTING.md
- README.md
List of changes from hackathon
* Clarified on main `README.md` what this repo is vs other similar ones like `tutorials`. The vast majority of open issues are support requests which need either better repros or need to go to discuss
* Updated `CONTRIBUTING.md`to make it clear how people should go about contributing new examples, bug fixes, error reports and tests
* Created templates for issues and pull requests to guide people to give us better repros - I still need to test these on my fork
* Curating `good first issue` we don't need to do everything ourselves -[ we have 40 and counting](https://github.com/pytorch/examples/labels/good%20first%20issue)
* I also need to disable circleci since it's not used for anything - haven't figured out where it's configured
There is also [another draft …
> clarifying what pytorch/examples is and how to contribute

- fast_neural_style/neural_style/neural_style.py
The old onnx implementations seemed to be outdated and didn't work properly for me.
I set the model to evaluation mode before transforming to onnx, I set the onnx opset_version to 11 (below there was a warning).
By running the onnx model I got the warning, that onnx_caffe2.backend only supports opset_version 2.
Therefore I followed the tutorial: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html to run the onnx model with onnxruntime instead.
I wasn't sure if I should leave the old function in the file with an option to run it, but I deleted to keep the file clean.
The new implementation only performs the final style transfer using the onnx model on the cpu, but that's the purpose of real time style transfer anyway.
> fast neural style: run onnxmodel using onnxruntime

- imagenet/main.py
> Use PyTorch Step Scheduler

- imagenet/README.md
- imagenet/extract_ILSVRC.sh
- imagenet/main.py
Added script in readme to manage extraction of both training and validation data in reference to: https://github.com/pytorch/examples/issues/933
> Change imagenet data script to include training data

- reinforcement_learning/actor_critic.py
- run_python_examples.sh
Minor update: `CartPole-v0` is out of date, therefore updated to `CartPole-v1`
> updated CartPole-v0 to CartPole-v1

- .github/workflows/main.yml
- .gitignore
- CONTRIBUTING.md
- docs/Makefile
- docs/make.bat
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
* Set up a docs directory for publishing 
* Add a job for GH actions
* Add index.rst as a landing page for the docs
> publish examples site 

- imagenet/main.py
If the dataset is not exactly divisible by world_size, the validation accuracy is incorrect. We solve this problem with an auxiliary validation set.
fix #769 close #907 #890
Signed-off-by: siaimes <34199488+siaimes@users.noreply.github.com>
Example results:
Note: ceil((50000 // 3) / int(256/3)) + 1 = 198 for 3 GPUs.
> If the dataset is not exactly divisible by world_size, the validation accuracy is incorrect. We solve this problem with an auxiliary validation set.

- reinforcement_learning/actor_critic.py
> Update actor_critic.py typo

- dcgan/README.md
- dcgan/main.py
- fast_neural_style/README.md
- fast_neural_style/neural_style/neural_style.py
- imagenet/main.py
- legacy/snli/train.py
- mnist/main.py
- mnist_hogwild/main.py
- run_python_examples.sh
- siamese_network/main.py
- super_resolution/README.md
- super_resolution/main.py
- vae/README.md
- vae/main.py
- word_language_model/README.md
- word_language_model/main.py
> Revert "Add mps device"

- dcgan/README.md
- dcgan/main.py
- fast_neural_style/README.md
- fast_neural_style/neural_style/neural_style.py
- imagenet/main.py
- legacy/snli/train.py
- mnist/main.py
- mnist_hogwild/main.py
- run_python_examples.sh
- siamese_network/main.py
- super_resolution/README.md
- super_resolution/main.py
- vae/README.md
- vae/main.py
- word_language_model/README.md
- word_language_model/main.py
Fixes for https://github.com/pytorch/examples/actions/runs/3057677630/jobs/4933077546
The final run passed "Run Examples" workflow
https://github.com/YuliyaPylypiv/examples/actions/runs/3086424730/jobs/4990755923
> Add mps device

- distributed/ddp-tutorial-series/multigpu.py
- distributed/ddp-tutorial-series/multigpu_torchrun.py
- distributed/ddp-tutorial-series/multinode.py
- distributed/minGPT-ddp/mingpt/trainer.py
Fixes issue reported in #1074  
cc: @hudeven
> Add set_epoch and fix args in DDP-series example

- distributed/ddp-tutorial-series/multigpu_torchrun.py
> Add map_location parameter in DDP-series example (pytorch#1078)

- mnist_rnn/README.md
- mnist_rnn/main.py
- mnist_rnn/requirements.txt
**Motivation:** Create pytorch example similar to Official Tensorflow Keras RNN example using MNIST [here](https://www.tensorflow.org/guide/keras/rnn)
I have written and tested the code by modifying following example on MNIST [here](https://github.com/pytorch/examples/tree/master/mnist) .
> Example of MNIST using RNN

- run_python_examples.sh
Fix CI failure brought in by rebase errors.
> Fix CI error in example

- word_language_model/model.py
More context for this change here: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with
> Fix exception causes in word_language_model/model.py

- distributed/minGPT-ddp/requirements.txt
FSSpec requires additional libraries: `aiohttp` and `requests`
~~~
(mingpt) ubuntu@ip-172-31-11-224:~/workspace/pytorch_examples/distributed/minGPT-ddp/mingpt$ MASTER_PORT=25000 MASTER_ADDR=$(hostname) RANK=0 WORLD_SIZE=1 python main.py
[2022-12-28 17:48:09,024][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 0
[2022-12-28 17:48:09,025][torch.distributed.distributed_c10d][INFO] - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Error executing job with overrides: []
File "/home/ubuntu/venv/mingpt/lib/python3.8/site-packages/fsspec/registry.py", line 243, in get_filesystem_class
register_implementation(protocol, _import_class(bit["class"]))
File …
> Update requirements.txt for minGPT ddp example

- siamese_network/main.py
Description :
The update removes warnings obtained on running the `main.py` file, contained in `siamese_network` folder
> Removes warnings displayed on running main.py

- CODEOWNERS
- README.md
- docs/source/index.rst
- mnist_forward_forward/README.md
- mnist_forward_forward/main.py
- mnist_forward_forward/requirements.txt
- run_python_examples.sh
this PR includes code for [Forward-Forward Algorithm](https://arxiv.org/abs/2212.13345),
as described in issue [#1111 ](https://github.com/pytorch/examples/issues/1111).
Thanks❤️,
Vivek V patel.
> Fixes #1111 : Added Forward-Forward Algorithm

- word_language_model/model.py
> Change ninp to nhid

- word_language_model/model.py
> Revert "Change ninp to nhid"

- distributed/ddp-tutorial-series/README.md
> Fix typo in README.md

- mnist_hogwild/README.md
- mnist_hogwild/main.py
I have also added README.md for the example as it was missing. Merging this PR closes #1188
> Added the --save_model arg for `mnist_hogwild` example

- vision_transformer/main.py
Correct the default value in the command line help.
> Fix args description

- imagenet/main.py
* ngpus_per_node variable count fix
* dist_backend assertion added for nccl issue
> Fixes in Imagenet training script

- imagenet/main.py
> Revert "Fixes in Imagenet training script"

- vision_transformer/README.md
added a missing ")" in  README.md
> fix minor typo in README.md

- LICENSE
> docs: added copyright holder to license file
